volumes:
  web_node_modules:

services:
  web:
    build:
      context: .
      target: ${NODE_ENV:-development}
      args:
        NODE_ENV: ${NODE_ENV:-development}
        NODE_CONFIG_ENV: ${NODE_CONFIG_ENV:-}
        BUILD: 1770282002
    volumes:
      - .:/app
      - web_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    profiles:
      - prod
