apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: betterweather

resources:
  - ../base
  - db-secret.yaml

patches:
  - path: web-service-patch.yaml
  - path: web-configmap-patch.yaml
  - path: web-deployment-patch.yaml

secretGenerator:
  - name: web-secret
    envs:
      - .env

generatorOptions:
  disableNameSuffixHash: true
