---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: betterweather
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCTGIOd2hpkeI11XzSw1ZZIanwCXww9B9o+B3t9VKXPBo8trtItK2k6o78spFMTapssPDyljB8smgggyCRaEysp/Gta14e6to+JnzFBl8qQg2jLr3bXc/hUME2+v/w039RDPVWszAnTHbDD23iiySPIPyPqO85BsN7uB8G8s7uFh6e15UyTo36/1LBatPxmHbYOyfX74rGKwG7X0F3gD+quv+n5i9sfM/j6FUl58P0IUH9bW87phBAQXHxpL6i9syH9L9mbuKkfYQ5xyvI1cjch9HuguVHq9hdZgjO3Fs5HN0r4icNhwLnPvyqrLompFu4hF8FhdNiMFN5xgXS/hvOhn2UkSEh4hXpc8OmqtiS2Nl3UXJhKOlOiCLAQfiDvX/HPssxw7vPcofFVV9njAeW24jgDpWEh7nC3I1z1QjVjP9sS1LRcepx/LrsRs77jMKq6L0Glw5cKDG9PbQhalTxlgPCeUl0LAXBibiiHpt2EBQvjfLBWnHHqe4OFb5Ud0QweiDvm2M75y8C0abwjXvGFanWxQ2A5tM5VJjvEDKpR9VsDlO4scDEW8YOt2Fo+VjbNqRafmaTlum6WJwcQgrerC/NAWvtXwBlp54GoQawGynkC3cdhHuIEFsmw3k+MQqw1s8Zv0ne1vg50bDRns2C/34yHW2lOU05DlJEsKM6jNGMMgJ9NS0s75D0dLaQbxtr52D69UDqyq0/gM+9isldQ
    DATABASE_URL: AgCeZ6xGljpmx9CORp+Se8vrVHViTtZrftamAOLN5KSYI63H0lXx2hief8IlkOL6S/jReIcX2HFWHQAVWRinqZbXBXPBO3ujnGOoIwKJ6NG6zq+YenzAeZUiOCOOKP0vLhZJPKampcZ1zi5PFGxVsvTPDIhRKywv6YW0lONWXr/3990jWf1hm2UJw7ZUTBIpsA+S2HcmdU0h2cZGzWbAl6rQtutov3qb6rGPtJkLf8RYhOTPntNrdQZr2Ti3ovloWQwhbwZsOdYz3TsIN3vAvnoJXcvm/RjphnXahxXoL1OO/7Yq1xvI/BSZ8lawOifMsBTK2+ww6n97IGfd2ojW+z0vvYB/F7z5S7RqotoVli5k0Bmvcqqz0t4plTJWB4cyJIwhjq84qroh9t9d81IJtlbs1G6ok3zr/1Mu/sfcHsthIF8y+K2UXxmGieD5E0uJeYkI802Hdg0UZmoSQShuWuks/AACJIC5i95aVTbXq9F94oPzQdjjPsqkHW6C/OJvt70mr8qCdctSTxqXImt0lL3E6sD1TAFfWVP8QjtFmk00uk2qI+NqXoHHaesRPGcnhXl5AvSjBGO+XCtbZ3c6uObUz4jGAit0g7WeUQ42nYDwd0CpLEG7723oUfYBkgCIpCfkL5M7VrTP3wZ6ZSdcjDvWSC+cquccOTRO2HpXn2n7ScZ+oD5dAC1NstXGSRBwStjWpsQFJGi4NuB1yiIbmo9aKpduWT0yGDgIc3wX3w4P70KEA/dNxtVob9ggS/yMyN0r5elthZrdBdthm4R5fEM=
  template:
    metadata:
      name: db-secret
      namespace: betterweather
