---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: betterweather
spec:
  encryptedData:
    DATABASE_URL: AgBgNZ/Dt/kbfiWK7PBLK6D9dBVNC4YyoXK6/g+dk8XPf1+5BBO+nOXHkPruFnYn/9oSVcMstli+GctBlF+rM+/pFdv3jBSJjIaM9Fs8HwpYyRxLP/CrxxFdmQ86bdjHzcRDo8oKJAz2Uevpp8kb7wHefM8c+6SIBidzdyRv/zwt0eXQzLzq5XcWOrCLAncLdeODwVck3j3A9EOhD/RkHXyCv9i9d8AyhZDIXOZG6qZV8MKP78vwuGXFWoTjU5HSoQ/n5+U+swy/bxXWB8M71hG2OiFI3A7HYq/IqSzy+01zC1vd42nsvaHIoXvuxsPQsdDPQp25kaZzS28aWgwK0mP5zqbzEdKN4rtLPn/f7Iy6pkMg0kPc7Q57+hW6hjxDYC3veYwHeAA3kcrh50Aju0o9RB/C1KEWp1s1dP8nOhR8tiEs8HMDrTRuue4xpRMhNuD03/XV7inZXOJP+FJB8snT1oiWH5zC/s/ROS2vnoegQAZy2+kNZASVIJZTylmi+HOq6wSECo9o1iQ1i0x3xHaIemW8LybFBDs/3Kg8FZ1N4HA3rNR2cLmdRkttLtz8lh2uRfuMpoVNtFdx2ZWeQTT+0r485P5pIdSQp32YnwYDiFLriGo+bBtJSMibXKLPDtK40YkF+/w4yRD78WLzfxhOWH/HbiHpqboq9/leHht66K+6szv7jjisXF2t8R7ypW/Lna5h+n/22552cgqj2WUgRUBpyu2z22N7lPga4yEi4/ajUnGgLHD1c7FZusoiR/GwRpKi88DdXvvq8+O6z9M=
    POSTGRES_PASSWORD: AgCIRA7k1qOmYIEtbOdBZXdbzX8JzhN2YDGR3kLzb2PnmW6QxbsAZ5uAMwzHUSW0mdJLDuHbGSZLmcqCP57h33/qIUUH0flrOKd39APzKYvPMeJ92cEDF8PB5n6G7/nXaYP1KTg1y0KqRJ9AowVd0GIq0x0/QC9nJKXxQlIvTX+urgrrgi0LJ5MZLn2Ez5mZ59J8vpX8Kn7/byIVXRj1wByZxxQthSbV6pKkKI3EOlXhGnlzWIzUesXfa7QaUpEsjnfiT27McShA2efvfVfGW4VEoQusPVkVw3ffbrPQF0XZepvsjQ+7MwhZO97YIrvtcun0pngzEc/R8zJt2OeYc7BzluC9LV9tXgfYuziGLr0F9ujm00mPIKj8Nav1SeM536L7w81Vdy9V1SDwvWKYMcaV78YCodNkf7vjYphgFI0q4BvrsrX8+P7DmgOfhbtxyfYX99jI0oLnSuj7HwRrqOyRlb0MaNiaqeDT2VY9Z4VRm4iTz6F9F7kwDzlGzy4QGjFoVbzrQ5rnWXdgk0n/98OWkoHH1Cvo7eSy6qnT8p9Jh6+F/r20EHRLjC9K901Tm2mZJuP8zzsqBsYF1Eb8AeaX8n1GqHIkHdzrNLO1hXmKnx0Xq/IuwujPZPPL1c3ePtHgZcFUggic0fXpP+s7NZQ2oQZhhXxFnFoKrFPQO1Jk7E1ytRvcFv6IwmAqPdpdn0hvDgxMm+o+SUoBIluu+6Ux
  template:
    metadata:
      name: db-secret
      namespace: betterweather
