---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: web-secret
  namespace: betterweather
spec:
  encryptedData:
    GOOGLE_MAPS_API_KEY: AgCVENhs4ex4Xl8ic8p/HjNChqBkc24+j8lSCG9Flr56z3Owen94mNalX3bKzZx3yLHya713rCrjA44jYPONG2epReAG/7IJKZCqpZ+jF/Auo2CZDKC1A6/tEyZLQW56DwU0oAtfQtJZ12DMX7kKDpF2O6S8kmPOz42Y41xZZ7a8Oe2GGmgB778vhd3wcR8cEa57K8UCuhtpHQkuqEqa09hGf2jXwL6S8f8wWScPGNDbAKPWUgOZVCpBrbsJycK5deEaHedHbrjiy3ydzjoArpCd4dDFuuk1wLk/ra27jFD+ebfq35O3E4352YpXJxVYleUtNxBv7M6Nlv/VgOdEy+vVndyuDLCbBVu2GS2GA1xVJGaKp2JKy5Qt0tYMVPEwZqh+ZKKRm+MQQMbpZ9ELKzhJk9HPNHiwhCkh8wGV4eAPEKzp3X2l18rx2OIXwRknqvoot/yBzfIag+Gd0sLfTs0A9VYFzNN6mI8b+5vOVqTUuiIsyUrCG9bMwD5xN6TZaGYgfQrClhy2ldUqmq82WHxSnX0t7GIuLNAtPg4VLC9LKCjOGltMi0UU5k5BZOTQw/FbpLltyCWnPHNGkszWBCdRIfWrcUHgPp3Mi4kcB0HG2PNXRM2EcHiUDDEBaBS5OdmHfXCBZh/srLWihJ4fpprNiveRfjD1d5spyxJm3DooclxEBR/7uBAKsApH2llKSpS1Ow5j2Vup7RKF8qaCllMH5NdcOuPfgGhTyk0VTEMKlLbxsjQNFRM=
  template:
    metadata:
      name: web-secret
      namespace: betterweather
