---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: web-secret
  namespace: betterweather
spec:
  encryptedData:
    GOOGLE_MAPS_API_KEY: AgA/rkcEwAqLYEclvrFJMWRaYj4EVJOr1WgmqAA+v8CLo357d6bEr425alOeK+ij3yN/9BUZlOFNaqQO5rgFdVpJQpj4S7o0GfBFnlA29hKbEbfniqIt8wZFFUO1r4RnZEjdxjb6kmOKE+ydy630/XKKi+Jk6nYYWvzYkoVLJu+dPvZIfGWCwRVMY/0gyUol1K73Qw4iHvfIyNjtiCCjVwCbzsODDk4QwEUCPxXEE48e4NhUD0JNdivXoSyG2leJARXshbo1aCxMvkCaCO4wdV9l30IK2qm6f7/e5n/kk+plbPT3N6rGCQrBovTxxN5+Fs/P2i6lU2km5OTnxO/ebWE9snmjQbtzcQ41wryLe4rxWxRjZyZjJN+YOtqgeygpMYHE+Z7bM5oUi165nIu9d9AJc8ul0cYjIZYeX6SI0wcPfldHIV9K3yOgZ2bQ8xnt3OZxI8w1VR4Nv+Hk/SbTushCe3CGWSXH6VEJG8pmYgKjjeVS0YB12iRUZUC6FFNfNkSO1iLNW1HybNt4C4HmpvQKBmdiArYNqPJTv5z4iX8Eq4bPv972hDZgF790Bfc/goe6T/MOThspTIa6g/Po4OVRLa61e39SdPlUsVQ+U2POz5Iu2aS5bI9cdMMnyuyOPWf+rCAq3B7AGpx6Hfh3ndI+CySHCiGeYWoCqtzONPcS10kyjDLit8kU8G3Y4cBU13LmMT8U0BZzVrSKvcVyxuTm59NB9khWkhyPuu+KzA9eFo6S8A07000=
    GOOGLE_WEATHER_API_KEY: AgBNrFldjuStz6HV4vMZgQ/8appF3g8whLGiGGQ9wni0rAouLDDREpsnYBHX72euKD+zVTHDr5RcjbDIcbAvp7kVaZ/745eD5uMJMF+BO0VEwQoNR2eHIFAYPaufUTNogeaIi7vlk2EmHeyVV30vPqtEPsO3o3lOkcVRG7W+b2oNhLzxvlOVSo6b+KC2Ui206jVrTl+6MqddTsQlb2IA2c4rD7fMbTwxRYNkHSbtn8cy9mio0621lgbLMASAYl0iH6jlJW/ua4TIMxWpXMKuVxnPVy162YSLDd1+hoKhQ5gs3LdUtetT7M/tP3MBuYu16sHwoKG0joCWyi7FfpdQ+Z4cdFILsjeVxUarL7KiGi8jzWTawn40q/1r8c7S+Pw8KiR1RJgNuOrM97HcXIG+0HHf7lZ84ZAqQSibe8fObAp1uDSyMcC6iBpRBzcvdeuCg9lLqUCpP40uJQ/gzMe92G5GxwTJWhpcEWyyGorPulPE4upvysbaDzYXoQpwiz96kxAbIPW/jC0s5GaMWBjcCkuEb7feUOAHtD1Z74XlCuSe2X6aJlYOIjnj8HtEe0yyA8tHW9KeXQl9xYbXJSwwFCVnC4tAWWCRRmgd+W2XMqo5R4CcZqDV4c2KDcM9YWat81vi4fad3HUKLynaTkbXqAitiy/pyQ11d5OelO9GoBbioVVJOJFLffyPjvFkrQ5pVrTs4o63DU4WBc96CJ9HEo31b3x8FqwDAzTl4lt+L26/QxrPuLakYoE=
  template:
    metadata:
      name: web-secret
      namespace: betterweather
